include: package:analysis_options_shared/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.gr.dart"
    - "lib/generated/**"
    - "**/*.mocks.dart"
